import { createServerFn } from "@tanstack/react-start";
import type { ModuleKey, ModulePermission } from "@/types";

type CreateTeamUserInput = {
  /** The CALLER's own Firebase ID token (await auth.currentUser.getIdToken()),
   * not the new user's — this is how the server independently verifies the
   * caller is really the owner, rather than trusting a client-side claim.
   * A server endpoint is reachable directly over the network regardless of
   * what the UI hides, so this check has to happen here, not in the browser. */
  callerIdToken: string;
  email: string;
  password: string;
  name: string;
  permissions: Partial<Record<ModuleKey, ModulePermission>>;
};

/** Lazily initializes the Admin SDK app exactly once per server process —
 * needs a service-account key, supplied via the FIREBASE_SERVICE_ACCOUNT_KEY
 * env var (the full JSON from Firebase Console → Project Settings → Service
 * Accounts → Generate new private key, as a single-line string). This is a
 * secret only the business owner can generate and supply — it can't be
 * generated by anyone else, and must never be committed to the repo. */
async function getAdminApp() {
  const admin = await import("firebase-admin");
  if (admin.apps.length) return admin.app();

  const raw = process.env.FIREBASE_SERVICE_ACCOUNT_KEY;
  if (!raw) {
    throw new Error(
      "FIREBASE_SERVICE_ACCOUNT_KEY is not set — add the Firebase Admin SDK service account " +
        "JSON (Project Settings → Service Accounts → Generate new private key) as an " +
        "environment variable before Team member creation can work.",
    );
  }
  const serviceAccount = JSON.parse(raw);
  return admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
  });
}

/** Same named Firestore database the client SDK uses — see DATABASE_ID in
 * src/lib/firebase.ts. Must match exactly, or this would write team member
 * docs into the wrong (default) database where the app never looks. */
const DATABASE_ID = "kinteshmobileacce";

/**
 * Creates a new team member's login + permissions doc, entirely server-side.
 * Client-side createUserWithEmailAndPassword would sign in as the NEW user
 * in the owner's own browser tab, kicking the owner out of their own
 * session — Admin SDK creation avoids that entirely, since it never touches
 * any browser's auth state.
 */
export const createTeamUserServerFn = createServerFn({ method: "POST" })
  .validator((data: unknown): CreateTeamUserInput => {
    const d = data as Partial<CreateTeamUserInput>;
    if (!d?.callerIdToken) throw new Error("Not authenticated");
    if (!d.email?.trim()) throw new Error("Email is required");
    if (!d.password || d.password.length < 6) throw new Error("Password must be at least 6 characters");
    if (!d.name?.trim()) throw new Error("Name is required");
    return {
      callerIdToken: d.callerIdToken,
      email: d.email.trim(),
      password: d.password,
      name: d.name.trim(),
      permissions: d.permissions ?? {},
    };
  })
  .handler(async ({ data }) => {
    const admin = await import("firebase-admin");
    const app = await getAdminApp();

    // Independently verify the caller is the owner — never trust the
    // client's own idea of whether it's allowed to be here.
    const decoded = await admin.auth(app).verifyIdToken(data.callerIdToken);
    const db = admin.firestore(app);
    db.settings({ databaseId: DATABASE_ID });
    const callerDoc = await db.doc(`teamUsers/${decoded.uid}`).get();
    const caller = callerDoc.data();
    if (!caller?.isOwner || caller.active !== true) {
      throw new Error("Only the business owner can add team members.");
    }

    const userRecord = await admin.auth(app).createUser({
      email: data.email,
      password: data.password,
      displayName: data.name,
    });

    // Admin SDK writes bypass Firestore rules by design — this is the one
    // trusted path allowed to create a non-owner teamUsers doc; every
    // other creation attempt is rejected by firestore.rules.
    await db.doc(`teamUsers/${userRecord.uid}`).set({
      id: userRecord.uid,
      email: data.email,
      name: data.name,
      isOwner: false,
      active: true,
      permissions: data.permissions,
      createdAt: new Date().toISOString(),
    });

    return { uid: userRecord.uid };
  });
